version: "3"

services:
  zzemacs:
    hostname: ubuntu-2204-zzemacs
    image: zhoujd/ubuntu-22.04-zzemacs:dev
    container_name: zzemacs-dev
    network_mode: bridge
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    ports:
      - 11022:22
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /etc/sysctl.conf:/etc/sysctl.conf
      - /data/work:/home/${USER}/work
      - $HOME/.ssh:/home/${USER}/.ssh
      - ${ZZEMACS_ROOT}:/home/${USER}/zzemacs
