version: "3"

services:
  zzemacs:
    hostname: ubuntu-2004-zzemacs
    image: zz/ubuntu-20.04-zzemacs:dev
    container_name: zzemacs-dev
    network_mode: bridge
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    ports:
      - 11022:22
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/security/limits.conf:/etc/security/limits.conf
      - ${ZZEMACS_ROOT}:/home/${USER}/zzemacs
      - ${ZZEMACS_TOP}/lab:/home/${USER}/lab
