## zzemacs dev

services:
  zzemacs:
    build:
      context: ../dockerfiles/dev/
      dockerfile: ubuntu-dev.dockerfile
      args:
        VARIANT: 22.04
    hostname: ubuntu-2204-zzemacs
    image: zhoujd/ubuntu-22.04-zzemacs:dev
    container_name: zzemacs-dev
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2222:22"
    env_file: .env
    restart: always
    command:
      - "run"
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/zzemacs:/home/${USER}/zzemacs
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - ${HOME}/work:/home/${USER}/work
