## Makefile

.PHONY: all ubuntu-base ubuntu-dev debian-base debian-dev
all: ubuntu-base ubuntu-dev debian-base debian-dev

ubuntu-base:
	make -C ubuntu-base

ubuntu-dev:
	make -C ubuntu-dev

debian-base:
	make -C debian-base

debian-dev:
	make -C debian-dev
