## zzemacs daemon

services:
  emacs-daemon:
    hostname: ubuntu-2204-daemon
    image: zhoujd/ubuntu-22.04-daemon:dev
    container_name: emacs-daemon
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2222:22"
    env_file: .env
    restart: always
    command:
      - "run"
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/zzemacs:/home/${USER}/zzemacs
      - ${HOME}/zzemacs/font:/home/${USER}/.fonts
      - ${HOME}/zzemacs/.emacs:/home/${USER}/.emacs
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - ${HOME}/work:/home/${USER}/work
