(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "abs" "accept" "alarm" "atan2" "bind" "binmode"
"bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown" "chr"
"chroot" "close" "closedir" "connect" "continue" "cos" "crypt" "dbmclose"
"dbmopen" "default" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork" "format"
"formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "given" "glob" "gmtime" "goto" "grep" "hex" "import" "index"
"int" "ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link"
"listen" "local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir"
"msgctl" "msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir"
"ord" "our" "pack" "package" "pipe" "pop" "pos" "print" "printf"
"prototype" "push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read"
"readdir" "readline" "readlink" "readpipe" "recv" "redo" "ref" "rename"
"require" "reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say"
"scalar" "seek" "seekdir" "select" "semctl" "semget" "semop" "send"
"setgrent" "sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent"
"setpwent" "setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread"
"shmwrite" "shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice"
"split" "sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr"
"symlink" "syscall" "sysopen" "sysread" "sysseek" "system" "syswrite"
"tell" "telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "when" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"ActivePerl" "ActivePerl::Config" "ActivePerl::DocTools"
"ActivePerl::DocTools::Pod" "ActivePerl::DocTools::TOC"
"ActivePerl::DocTools::TOC::HTML" "ActivePerl::DocTools::TOC::RDF"
"ActivePerl::DocTools::TOC::tocTab" "ActivePerl::DocTools::TOC::tocxml"
"ActivePerl::DocTools::Tree::HTML" "ActivePerl::PPM"
"ActivePerl::PPM::Arch" "ActivePerl::PPM::Client" "ActivePerl::PPM::DBH"
"ActivePerl::PPM::GUI" "ActivePerl::PPM::InstallArea"
"ActivePerl::PPM::Logger" "ActivePerl::PPM::PPD" "ActivePerl::PPM::Package"
"ActivePerl::PPM::ParsePPD" "ActivePerl::PPM::Profile"
"ActivePerl::PPM::RepoPackage" "ActivePerl::PPM::Status"
"ActivePerl::PPM::Status::Term" "ActivePerl::PPM::Util"
"ActivePerl::PPM::Web" "ActivePerl::PPM::limited_inc"
"ActiveState::Browser" "ActiveState::Bytes" "ActiveState::CPAN"
"ActiveState::CPAN::Makefile_PL" "ActiveState::CPAN::Utils"
"ActiveState::Color" "ActiveState::Config::INI" "ActiveState::DateTime"
"ActiveState::DiskUsage" "ActiveState::Duration" "ActiveState::Handy"
"ActiveState::Indenter" "ActiveState::Menu" "ActiveState::ModInfo"
"ActiveState::OSType" "ActiveState::Path" "ActiveState::PerlCritic::Policy"
"ActiveState::PerlCritic::UserProfile"
"ActiveState::PerlCritic::UserProfile::Policy"
"ActiveState::PerlCritic::Util" "ActiveState::Prompt"
"ActiveState::RelocateTree" "ActiveState::Run" "ActiveState::Scineplex"
"ActiveState::Scineplex::Constants" "ActiveState::StopWatch"
"ActiveState::Table" "ActiveState::Tkx" "ActiveState::Tkx::TextSyntaxTags"
"ActiveState::Tkx::Util" "ActiveState::Tkx::Widget" "ActiveState::Version"
"ActiveState::Win32::Shell" "Algorithm::C3" "Algorithm::Diff"
"Algorithm::DiffOld" "AnyDBM_File" "App::Cpan" "App::Prove"
"App::Prove::State" "App::Prove::State::Result"
"App::Prove::State::Result::Test" "Archive::Extract" "Archive::Tar"
"Archive::Tar::Constant" "Archive::Tar::File" "Archive::Zip"
"Archive::Zip::Archive" "Archive::Zip::BufferedFileHandle"
"Archive::Zip::DirectoryMember" "Archive::Zip::FAQ"
"Archive::Zip::FileMember" "Archive::Zip::Member"
"Archive::Zip::MemberRead" "Archive::Zip::MockFileHandle"
"Archive::Zip::NewFileMember" "Archive::Zip::StringMember"
"Archive::Zip::Tree" "Archive::Zip::ZipFileMember" "Attribute::Handlers"
"AutoLoader" "AutoSplit" "B" "B::Concise" "B::Debug" "B::Deparse"
"B::Keywords" "B::Lint" "B::Lint::Debug" "B::Showlex" "B::Terse" "B::Xref"
"Benchmark" "Bit::Vector" "Bit::Vector::Overload" "Bit::Vector::String"
"Bundle::DBD::CSV" "Bundle::DBD::Pg" "Bundle::DBI" "CGI" "CGI::Apache"
"CGI::Carp" "CGI::Cookie" "CGI::Fast" "CGI::Pretty" "CGI::Push"
"CGI::Switch" "CGI::Util" "CORE" "CPAN" "CPAN::API::HOWTO" "CPAN::Author"
"CPAN::Bundle" "CPAN::CacheMgr" "CPAN::Complete" "CPAN::Config"
"CPAN::Debug" "CPAN::DeferredCode" "CPAN::Distribution" "CPAN::Distroprefs"
"CPAN::Distrostatus" "CPAN::Exception::RecursiveDependency"
"CPAN::Exception::blocked_urllist" "CPAN::Exception::yaml_not_installed"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HTTP::Client"
"CPAN::HTTP::Credentials" "CPAN::HandleConfig" "CPAN::Index"
"CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Meta"
"CPAN::Meta::Converter" "CPAN::Meta::Feature" "CPAN::Meta::History"
"CPAN::Meta::Prereqs" "CPAN::Meta::Spec" "CPAN::Meta::Validator"
"CPAN::Meta::YAML" "CPAN::Mirrors" "CPAN::Module" "CPAN::Nox"
"CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip" "CPAN::URL"
"CPAN::Version" "CPANPLUS" "CPANPLUS::Backend" "CPANPLUS::Backend::RV"
"CPANPLUS::Config" "CPANPLUS::Configure" "CPANPLUS::Configure::Setup"
"CPANPLUS::Dist" "CPANPLUS::Dist::Autobundle" "CPANPLUS::Dist::Base"
"CPANPLUS::Dist::Build" "CPANPLUS::Dist::Build::Constants"
"CPANPLUS::Dist::MM" "CPANPLUS::Dist::Sample" "CPANPLUS::Error"
"CPANPLUS::FAQ" "CPANPLUS::Hacking" "CPANPLUS::Internals"
"CPANPLUS::Internals::Constants" "CPANPLUS::Internals::Constants::Report"
"CPANPLUS::Internals::Extract" "CPANPLUS::Internals::Fetch"
"CPANPLUS::Internals::Report" "CPANPLUS::Internals::Search"
"CPANPLUS::Internals::Source" "CPANPLUS::Internals::Source::Memory"
"CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::HOWTO"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Carp" "Carp::Clan"
"Carp::Heavy" "Class::Accessor" "Class::Accessor::Fast"
"Class::Accessor::Faster" "Class::C3" "Class::C3::next"
"Class::Data::Inheritable" "Class::MOP" "Class::MOP::Attribute"
"Class::MOP::Class" "Class::MOP::Class::Immutable::Trait"
"Class::MOP::Deprecated" "Class::MOP::Instance" "Class::MOP::Method"
"Class::MOP::Method::Accessor" "Class::MOP::Method::Constructor"
"Class::MOP::Method::Generated" "Class::MOP::Method::Inlined"
"Class::MOP::Method::Meta" "Class::MOP::Method::Wrapped"
"Class::MOP::MiniTrait" "Class::MOP::Mixin"
"Class::MOP::Mixin::AttributeCore" "Class::MOP::Mixin::HasAttributes"
"Class::MOP::Mixin::HasMethods" "Class::MOP::Module" "Class::MOP::Object"
"Class::MOP::Package" "Class::Struct" "Clone" "Compress::Raw::Bzip2"
"Compress::Raw::Zlib" "Compress::Zlib" "Config" "Config::Extensions"
"Config::Tiny" "Cwd" "DB" "DBD::CSV" "DBD::DBM" "DBD::ExampleP" "DBD::File"
"DBD::File::Developers" "DBD::File::HowTo" "DBD::File::Roadmap"
"DBD::Gofer" "DBD::Gofer::Policy::Base" "DBD::Gofer::Policy::classic"
"DBD::Gofer::Policy::pedantic" "DBD::Gofer::Policy::rush"
"DBD::Gofer::Transport::Base" "DBD::Gofer::Transport::corostream"
"DBD::Gofer::Transport::null" "DBD::Gofer::Transport::pipeone"
"DBD::Gofer::Transport::stream" "DBD::NullP" "DBD::ODBC"
"DBD::ODBC::Changes" "DBD::ODBC::FAQ" "DBD::ODBC::TO_DO" "DBD::Oracle"
"DBD::Oracle::GetInfo" "DBD::Oracle::Object" "DBD::Pg" "DBD::Proxy"
"DBD::SQLite" "DBD::SQLite::Cookbook" "DBD::Sponge" "DBI" "DBI::Changes"
"DBI::Const::GetInfo::ANSI" "DBI::Const::GetInfo::ODBC"
"DBI::Const::GetInfoReturn" "DBI::Const::GetInfoType" "DBI::DBD"
"DBI::DBD::Metadata" "DBI::DBD::SqlEngine"
"DBI::DBD::SqlEngine::Developers" "DBI::DBD::SqlEngine::HowTo" "DBI::FAQ"
"DBI::Gofer::Execute" "DBI::Gofer::Request" "DBI::Gofer::Response"
"DBI::Gofer::Serializer::Base" "DBI::Gofer::Serializer::DataDumper"
"DBI::Gofer::Serializer::Storable" "DBI::Gofer::Transport::Base"
"DBI::Gofer::Transport::pipeone" "DBI::Gofer::Transport::stream"
"DBI::Profile" "DBI::ProfileData" "DBI::ProfileDumper"
"DBI::ProfileDumper::Apache" "DBI::ProfileSubs" "DBI::ProxyServer"
"DBI::PurePerl" "DBI::SQL::Nano" "DBI::Util::CacheMemory"
"DBI::Util::_accessor" "DBI::W32ODBC" "DBM_Filter" "DBM_Filter::compress"
"DBM_Filter::encode" "DBM_Filter::int32" "DBM_Filter::null"
"DBM_Filter::utf8" "Data::Dump" "Data::Dump::FilterContext"
"Data::Dump::Filtered" "Data::Dump::Trace" "Data::Dumper" "Data::OptList"
"Date::Calc" "Date::Calc::Object" "Date::Calc::PP" "Date::Calendar"
"Date::Calendar::Profiles" "Date::Calendar::Year" "Devel::DProf"
"Devel::DProf::V" "Devel::GlobalDestruction" "Devel::InnerPackage"
"Devel::NYTProf" "Devel::NYTProf::Apache" "Devel::NYTProf::Constants"
"Devel::NYTProf::Core" "Devel::NYTProf::Data" "Devel::NYTProf::FileHandle"
"Devel::NYTProf::FileInfo" "Devel::NYTProf::ReadStream"
"Devel::NYTProf::Reader" "Devel::NYTProf::Run" "Devel::NYTProf::SubInfo"
"Devel::NYTProf::Test" "Devel::NYTProf::Util" "Devel::PPPort" "Devel::Peek"
"Devel::SelfStubber" "Devel::StackTrace" "Devel::StackTrace::Frame"
"Digest" "Digest::HMAC" "Digest::HMAC_MD5" "Digest::HMAC_SHA1"
"Digest::MD5" "Digest::SHA" "Digest::SHA1" "Digest::base" "Digest::file"
"DirHandle" "Dist::CheckConflicts" "Dumpvalue" "DynaLoader"
"Email::Address" "Encode" "Encode::Alias" "Encode::Byte"
"Encode::CJKConstants" "Encode::CN" "Encode::CN::HZ" "Encode::Config"
"Encode::EBCDIC" "Encode::Encoder" "Encode::Encoding" "Encode::GSM0338"
"Encode::Guess" "Encode::JP" "Encode::JP::H2Z" "Encode::JP::JIS7"
"Encode::KR" "Encode::KR::2022_KR" "Encode::Locale" "Encode::MIME::Header"
"Encode::MIME::Header::ISO_2022_JP" "Encode::MIME::Name" "Encode::PerlIO"
"Encode::Supported" "Encode::Symbol" "Encode::TW" "Encode::Unicode"
"Encode::Unicode::UTF7" "English" "Env" "Errno" "Eval::Closure"
"Exception::Class" "Exception::Class::Base" "Exporter" "Exporter::Heavy"
"ExtUtils::CBuilder" "ExtUtils::CBuilder::Base"
"ExtUtils::CBuilder::Platform::Unix" "ExtUtils::CBuilder::Platform::VMS"
"ExtUtils::CBuilder::Platform::Windows"
"ExtUtils::CBuilder::Platform::Windows::BCC"
"ExtUtils::CBuilder::Platform::Windows::GCC"
"ExtUtils::CBuilder::Platform::Windows::MSVC"
"ExtUtils::CBuilder::Platform::aix" "ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::MakeMaker::YAML" "ExtUtils::Manifest" "ExtUtils::Miniperl"
"ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists" "ExtUtils::Packlist"
"ExtUtils::ParseXS" "ExtUtils::ParseXS::Constants"
"ExtUtils::ParseXS::CountLines" "ExtUtils::ParseXS::Utilities"
"ExtUtils::Typemaps" "ExtUtils::Typemaps::InputMap"
"ExtUtils::Typemaps::OutputMap" "ExtUtils::Typemaps::Type"
"ExtUtils::testlib" "Fatal" "Fcntl" "File::Basename" "File::CheckTree"
"File::Compare" "File::Copy" "File::DosGlob" "File::Fetch" "File::Find"
"File::Glob" "File::GlobMapper" "File::HomeDir" "File::HomeDir::Darwin"
"File::HomeDir::Darwin::Carbon" "File::HomeDir::Darwin::Cocoa"
"File::HomeDir::Driver" "File::HomeDir::FreeDesktop"
"File::HomeDir::MacOS9" "File::HomeDir::Test" "File::HomeDir::Unix"
"File::HomeDir::Windows" "File::Listing" "File::Next" "File::Path"
"File::Spec" "File::Spec::Cygwin" "File::Spec::Epoc"
"File::Spec::Functions" "File::Spec::Mac" "File::Spec::OS2"
"File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32" "File::Temp"
"File::Which" "File::stat" "FileCache" "FileHandle" "Filter::Simple"
"Filter::Util::Call" "FindBin" "GD" "GD::Graph" "GD::Graph::Data"
"GD::Graph::Error" "GD::Graph::FAQ" "GD::Graph::area" "GD::Graph::axestype"
"GD::Graph::bars" "GD::Graph::colour" "GD::Graph::hbars" "GD::Graph::lines"
"GD::Graph::linespoints" "GD::Graph::mixed" "GD::Graph::pie"
"GD::Graph::points" "GD::Graph::utils" "GD::Group" "GD::Image"
"GD::Polygon" "GD::Polyline" "GD::Simple" "GD::Text" "GD::Text::Align"
"GD::Text::Wrap" "Getopt::Long" "Getopt::Std" "HTML::AsSubs"
"HTML::Element" "HTML::Element::traverse" "HTML::Entities" "HTML::Filter"
"HTML::Form" "HTML::HeadParser" "HTML::LinkExtor" "HTML::Parse"
"HTML::Parser" "HTML::PullParser" "HTML::Tagset" "HTML::Template"
"HTML::Template::FAQ" "HTML::TokeParser" "HTML::Tree"
"HTML::Tree::AboutObjects" "HTML::Tree::AboutTrees" "HTML::Tree::Scanning"
"HTML::TreeBuilder" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "HTTP::Tiny"
"Hash::Util" "Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "IO"
"IO::Compress::Adapter::Bzip2" "IO::Compress::Adapter::Deflate"
"IO::Compress::Adapter::Identity" "IO::Compress::Base"
"IO::Compress::Base::Common" "IO::Compress::Bzip2" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants"
"IO::Compress::RawDeflate" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle" "IO::Pipe"
"IO::Poll" "IO::Seekable" "IO::Select" "IO::Socket" "IO::Socket::INET"
"IO::Socket::SSL" "IO::Socket::UNIX" "IO::String"
"IO::Uncompress::Adapter::Bunzip2" "IO::Uncompress::Adapter::Identity"
"IO::Uncompress::Adapter::Inflate" "IO::Uncompress::AnyInflate"
"IO::Uncompress::AnyUncompress" "IO::Uncompress::Base"
"IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Zlib" "IPC::Cmd" "IPC::Open2" "IPC::Open3"
"JSON" "JSON::Any" "JSON::PP" "JSON::PP::Boolean" "JSON::backportPP"
"JSON::backportPP::Boolean" "JSON::backportPP::Compat5005"
"JSON::backportPP::Compat5006" "LWP" "LWP::Authen::Basic"
"LWP::Authen::Digest" "LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug"
"LWP::DebugFile" "LWP::MediaTypes" "LWP::MemberMixin" "LWP::Protocol"
"LWP::Protocol::GHTTP" "LWP::Protocol::cpan" "LWP::Protocol::data"
"LWP::Protocol::file" "LWP::Protocol::ftp" "LWP::Protocol::gopher"
"LWP::Protocol::http" "LWP::Protocol::https" "LWP::Protocol::loopback"
"LWP::Protocol::mailto" "LWP::Protocol::nntp" "LWP::Protocol::nogo"
"LWP::RobotUA" "LWP::Simple" "LWP::UserAgent" "List::MoreUtils"
"List::Util" "List::Util::PP" "List::Util::XS" "Locale::Codes"
"Locale::Codes::API" "Locale::Codes::Changes" "Locale::Codes::Constants"
"Locale::Codes::Country" "Locale::Codes::Country_Codes"
"Locale::Codes::Currency" "Locale::Codes::Currency_Codes"
"Locale::Codes::LangExt" "Locale::Codes::LangExt_Codes"
"Locale::Codes::LangVar" "Locale::Codes::LangVar_Codes"
"Locale::Codes::Language" "Locale::Codes::Language_Codes"
"Locale::Codes::Script" "Locale::Codes::Script_Codes" "Locale::Constants"
"Locale::Country" "Locale::Currency" "Locale::Language" "Locale::Maketext"
"Locale::Maketext::Cookbook" "Locale::Maketext::Guts"
"Locale::Maketext::GutsLoader" "Locale::Maketext::Simple"
"Locale::Maketext::TPJ13" "Locale::Script" "Log::Message"
"Log::Message::Config" "Log::Message::Handlers" "Log::Message::Item"
"Log::Message::Simple" "MIME::Base64" "MIME::QuotedPrint" "MRO::Compat"
"Math::BigFloat" "Math::BigFloat::Trace" "Math::BigInt"
"Math::BigInt::Calc" "Math::BigInt::CalcEmu" "Math::BigInt::FastCalc"
"Math::BigInt::Trace" "Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Build" "Module::Build::API"
"Module::Build::Authoring" "Module::Build::Base" "Module::Build::Bundling"
"Module::Build::Compat" "Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Load" "Module::Load::Conditional" "Module::Loaded"
"Module::Metadata" "Module::Pluggable" "Module::Pluggable::Object" "Moose"
"Moose::Conflicts" "Moose::Cookbook" "Moose::Cookbook::Basics::Recipe1"
"Moose::Cookbook::Basics::Recipe10" "Moose::Cookbook::Basics::Recipe11"
"Moose::Cookbook::Basics::Recipe2" "Moose::Cookbook::Basics::Recipe3"
"Moose::Cookbook::Basics::Recipe4" "Moose::Cookbook::Basics::Recipe5"
"Moose::Cookbook::Basics::Recipe6" "Moose::Cookbook::Basics::Recipe7"
"Moose::Cookbook::Basics::Recipe8" "Moose::Cookbook::Basics::Recipe9"
"Moose::Cookbook::Extending::Recipe1" "Moose::Cookbook::Extending::Recipe2"
"Moose::Cookbook::Extending::Recipe3" "Moose::Cookbook::Extending::Recipe4"
"Moose::Cookbook::Meta::Recipe1" "Moose::Cookbook::Meta::Recipe2"
"Moose::Cookbook::Meta::Recipe3" "Moose::Cookbook::Meta::Recipe4"
"Moose::Cookbook::Meta::Recipe5" "Moose::Cookbook::Meta::Recipe6"
"Moose::Cookbook::Meta::Recipe7" "Moose::Cookbook::Roles::Recipe1"
"Moose::Cookbook::Roles::Recipe2" "Moose::Cookbook::Roles::Recipe3"
"Moose::Cookbook::Snack::Keywords" "Moose::Cookbook::Snack::Types"
"Moose::Cookbook::Style" "Moose::Deprecated" "Moose::Error::Confess"
"Moose::Error::Croak" "Moose::Error::Default" "Moose::Error::Util"
"Moose::Exporter" "Moose::Intro" "Moose::Manual"
"Moose::Manual::Attributes" "Moose::Manual::BestPractices"
"Moose::Manual::Classes" "Moose::Manual::Concepts"
"Moose::Manual::Construction" "Moose::Manual::Contributing"
"Moose::Manual::Delegation" "Moose::Manual::Delta" "Moose::Manual::FAQ"
"Moose::Manual::MOP" "Moose::Manual::MethodModifiers"
"Moose::Manual::MooseX" "Moose::Manual::Roles" "Moose::Manual::Support"
"Moose::Manual::Types" "Moose::Manual::Unsweetened"
"Moose::Meta::Attribute" "Moose::Meta::Attribute::Native"
"Moose::Meta::Attribute::Native::Trait"
"Moose::Meta::Attribute::Native::Trait::Array"
"Moose::Meta::Attribute::Native::Trait::Bool"
"Moose::Meta::Attribute::Native::Trait::Code"
"Moose::Meta::Attribute::Native::Trait::Counter"
"Moose::Meta::Attribute::Native::Trait::Hash"
"Moose::Meta::Attribute::Native::Trait::Number"
"Moose::Meta::Attribute::Native::Trait::String" "Moose::Meta::Class"
"Moose::Meta::Class::Immutable::Trait" "Moose::Meta::Instance"
"Moose::Meta::Method" "Moose::Meta::Method::Accessor"
"Moose::Meta::Method::Accessor::Native"
"Moose::Meta::Method::Accessor::Native::Array"
"Moose::Meta::Method::Accessor::Native::Array::Writer"
"Moose::Meta::Method::Accessor::Native::Array::accessor"
"Moose::Meta::Method::Accessor::Native::Array::clear"
"Moose::Meta::Method::Accessor::Native::Array::count"
"Moose::Meta::Method::Accessor::Native::Array::delete"
"Moose::Meta::Method::Accessor::Native::Array::elements"
"Moose::Meta::Method::Accessor::Native::Array::first"
"Moose::Meta::Method::Accessor::Native::Array::first_index"
"Moose::Meta::Method::Accessor::Native::Array::get"
"Moose::Meta::Method::Accessor::Native::Array::grep"
"Moose::Meta::Method::Accessor::Native::Array::insert"
"Moose::Meta::Method::Accessor::Native::Array::is_empty"
"Moose::Meta::Method::Accessor::Native::Array::join"
"Moose::Meta::Method::Accessor::Native::Array::map"
"Moose::Meta::Method::Accessor::Native::Array::natatime"
"Moose::Meta::Method::Accessor::Native::Array::pop"
"Moose::Meta::Method::Accessor::Native::Array::push"
"Moose::Meta::Method::Accessor::Native::Array::reduce"
"Moose::Meta::Method::Accessor::Native::Array::set"
"Moose::Meta::Method::Accessor::Native::Array::shallow_clone"
"Moose::Meta::Method::Accessor::Native::Array::shift"
"Moose::Meta::Method::Accessor::Native::Array::shuffle"
"Moose::Meta::Method::Accessor::Native::Array::sort"
"Moose::Meta::Method::Accessor::Native::Array::sort_in_place"
"Moose::Meta::Method::Accessor::Native::Array::splice"
"Moose::Meta::Method::Accessor::Native::Array::uniq"
"Moose::Meta::Method::Accessor::Native::Array::unshift"
"Moose::Meta::Method::Accessor::Native::Bool::not"
"Moose::Meta::Method::Accessor::Native::Bool::set"
"Moose::Meta::Method::Accessor::Native::Bool::toggle"
"Moose::Meta::Method::Accessor::Native::Bool::unset"
"Moose::Meta::Method::Accessor::Native::Code::execute"
"Moose::Meta::Method::Accessor::Native::Code::execute_method"
"Moose::Meta::Method::Accessor::Native::Collection"
"Moose::Meta::Method::Accessor::Native::Counter::Writer"
"Moose::Meta::Method::Accessor::Native::Counter::dec"
"Moose::Meta::Method::Accessor::Native::Counter::inc"
"Moose::Meta::Method::Accessor::Native::Counter::reset"
"Moose::Meta::Method::Accessor::Native::Counter::set"
"Moose::Meta::Method::Accessor::Native::Hash"
"Moose::Meta::Method::Accessor::Native::Hash::Writer"
"Moose::Meta::Method::Accessor::Native::Hash::accessor"
"Moose::Meta::Method::Accessor::Native::Hash::clear"
"Moose::Meta::Method::Accessor::Native::Hash::count"
"Moose::Meta::Method::Accessor::Native::Hash::defined"
"Moose::Meta::Method::Accessor::Native::Hash::delete"
"Moose::Meta::Method::Accessor::Native::Hash::elements"
"Moose::Meta::Method::Accessor::Native::Hash::exists"
"Moose::Meta::Method::Accessor::Native::Hash::get"
"Moose::Meta::Method::Accessor::Native::Hash::is_empty"
"Moose::Meta::Method::Accessor::Native::Hash::keys"
"Moose::Meta::Method::Accessor::Native::Hash::kv"
"Moose::Meta::Method::Accessor::Native::Hash::set"
"Moose::Meta::Method::Accessor::Native::Hash::shallow_clone"
"Moose::Meta::Method::Accessor::Native::Hash::values"
"Moose::Meta::Method::Accessor::Native::Number::abs"
"Moose::Meta::Method::Accessor::Native::Number::add"
"Moose::Meta::Method::Accessor::Native::Number::div"
"Moose::Meta::Method::Accessor::Native::Number::mod"
"Moose::Meta::Method::Accessor::Native::Number::mul"
"Moose::Meta::Method::Accessor::Native::Number::set"
"Moose::Meta::Method::Accessor::Native::Number::sub"
"Moose::Meta::Method::Accessor::Native::Reader"
"Moose::Meta::Method::Accessor::Native::String::append"
"Moose::Meta::Method::Accessor::Native::String::chomp"
"Moose::Meta::Method::Accessor::Native::String::chop"
"Moose::Meta::Method::Accessor::Native::String::clear"
"Moose::Meta::Method::Accessor::Native::String::inc"
"Moose::Meta::Method::Accessor::Native::String::length"
"Moose::Meta::Method::Accessor::Native::String::match"
"Moose::Meta::Method::Accessor::Native::String::prepend"
"Moose::Meta::Method::Accessor::Native::String::replace"
"Moose::Meta::Method::Accessor::Native::String::substr"
"Moose::Meta::Method::Accessor::Native::Writer"
"Moose::Meta::Method::Augmented" "Moose::Meta::Method::Constructor"
"Moose::Meta::Method::Delegation" "Moose::Meta::Method::Destructor"
"Moose::Meta::Method::Meta" "Moose::Meta::Method::Overridden"
"Moose::Meta::Mixin::AttributeCore" "Moose::Meta::Object::Trait"
"Moose::Meta::Role" "Moose::Meta::Role::Application"
"Moose::Meta::Role::Application::RoleSummation"
"Moose::Meta::Role::Application::ToClass"
"Moose::Meta::Role::Application::ToInstance"
"Moose::Meta::Role::Application::ToRole" "Moose::Meta::Role::Attribute"
"Moose::Meta::Role::Composite" "Moose::Meta::Role::Method"
"Moose::Meta::Role::Method::Conflicting"
"Moose::Meta::Role::Method::Required" "Moose::Meta::TypeCoercion"
"Moose::Meta::TypeCoercion::Union" "Moose::Meta::TypeConstraint"
"Moose::Meta::TypeConstraint::Class"
"Moose::Meta::TypeConstraint::DuckType" "Moose::Meta::TypeConstraint::Enum"
"Moose::Meta::TypeConstraint::Parameterizable"
"Moose::Meta::TypeConstraint::Parameterized"
"Moose::Meta::TypeConstraint::Registry" "Moose::Meta::TypeConstraint::Role"
"Moose::Meta::TypeConstraint::Union" "Moose::Object" "Moose::Role"
"Moose::Spec::Role" "Moose::Unsweetened" "Moose::Util"
"Moose::Util::MetaRole" "Moose::Util::TypeConstraints"
"Moose::Util::TypeConstraints::Builtins" "Mozilla::CA" "NEXT" "Net::Cmd"
"Net::Config" "Net::Domain" "Net::FTP" "Net::FTP::A" "Net::FTP::E"
"Net::FTP::I" "Net::FTP::L" "Net::FTP::dataconn" "Net::HTTP"
"Net::HTTP::Methods" "Net::HTTP::NB" "Net::HTTPS" "Net::NNTP" "Net::Netrc"
"Net::POP3" "Net::Ping" "Net::SMTP" "Net::SSLeay" "Net::SSLeay::Handle"
"Net::Telnet" "Net::Time" "Net::hostent" "Net::libnetFAQ" "Net::netent"
"Net::protoent" "Net::servent" "O" "OLE" "Object::Accessor" "Opcode"
"Oraperl" "POSIX" "PPI" "PPI::Cache" "PPI::Document" "PPI::Document::File"
"PPI::Document::Fragment" "PPI::Document::Normalized" "PPI::Dumper"
"PPI::Element" "PPI::Exception" "PPI::Exception::ParserRejection"
"PPI::Exception::ParserTimeout" "PPI::Find" "PPI::Lexer" "PPI::Node"
"PPI::Normal" "PPI::Normal::Standard" "PPI::Statement"
"PPI::Statement::Break" "PPI::Statement::Compound" "PPI::Statement::Data"
"PPI::Statement::End" "PPI::Statement::Expression" "PPI::Statement::Given"
"PPI::Statement::Include" "PPI::Statement::Include::Perl6"
"PPI::Statement::Null" "PPI::Statement::Package"
"PPI::Statement::Scheduled" "PPI::Statement::Sub" "PPI::Statement::Unknown"
"PPI::Statement::UnmatchedBrace" "PPI::Statement::Variable"
"PPI::Statement::When" "PPI::Structure" "PPI::Structure::Block"
"PPI::Structure::Condition" "PPI::Structure::Constructor"
"PPI::Structure::For" "PPI::Structure::Given" "PPI::Structure::List"
"PPI::Structure::Subscript" "PPI::Structure::Unknown"
"PPI::Structure::When" "PPI::Token" "PPI::Token::ArrayIndex"
"PPI::Token::Attribute" "PPI::Token::BOM" "PPI::Token::Cast"
"PPI::Token::Comment" "PPI::Token::DashedWord" "PPI::Token::Data"
"PPI::Token::End" "PPI::Token::HereDoc" "PPI::Token::Label"
"PPI::Token::Magic" "PPI::Token::Number" "PPI::Token::Number::Binary"
"PPI::Token::Number::Exp" "PPI::Token::Number::Float"
"PPI::Token::Number::Hex" "PPI::Token::Number::Octal"
"PPI::Token::Number::Version" "PPI::Token::Operator" "PPI::Token::Pod"
"PPI::Token::Prototype" "PPI::Token::Quote" "PPI::Token::Quote::Double"
"PPI::Token::Quote::Interpolate" "PPI::Token::Quote::Literal"
"PPI::Token::Quote::Single" "PPI::Token::QuoteLike"
"PPI::Token::QuoteLike::Backtick" "PPI::Token::QuoteLike::Command"
"PPI::Token::QuoteLike::Readline" "PPI::Token::QuoteLike::Regexp"
"PPI::Token::QuoteLike::Words" "PPI::Token::Regexp"
"PPI::Token::Regexp::Match" "PPI::Token::Regexp::Substitute"
"PPI::Token::Regexp::Transliterate" "PPI::Token::Separator"
"PPI::Token::Structure" "PPI::Token::Symbol" "PPI::Token::Unknown"
"PPI::Token::Whitespace" "PPI::Token::Word" "PPI::Token::_QuoteEngine"
"PPI::Token::_QuoteEngine::Full" "PPI::Token::_QuoteEngine::Simple"
"PPI::Tokenizer" "PPI::Transform" "PPI::Transform::UpdateCopyright"
"PPI::Util" "PPI::XSAccessor" "PPIx::Regexp" "PPIx::Regexp::Constant"
"PPIx::Regexp::Dumper" "PPIx::Regexp::Element" "PPIx::Regexp::Lexer"
"PPIx::Regexp::Node" "PPIx::Regexp::Node::Range" "PPIx::Regexp::Structure"
"PPIx::Regexp::Structure::Assertion" "PPIx::Regexp::Structure::BranchReset"
"PPIx::Regexp::Structure::Capture" "PPIx::Regexp::Structure::CharClass"
"PPIx::Regexp::Structure::Code" "PPIx::Regexp::Structure::Main"
"PPIx::Regexp::Structure::Modifier" "PPIx::Regexp::Structure::NamedCapture"
"PPIx::Regexp::Structure::Quantifier" "PPIx::Regexp::Structure::Regexp"
"PPIx::Regexp::Structure::Replacement"
"PPIx::Regexp::Structure::Subexpression" "PPIx::Regexp::Structure::Switch"
"PPIx::Regexp::Structure::Unknown" "PPIx::Regexp::Support"
"PPIx::Regexp::Token" "PPIx::Regexp::Token::Assertion"
"PPIx::Regexp::Token::Backreference" "PPIx::Regexp::Token::Backtrack"
"PPIx::Regexp::Token::CharClass" "PPIx::Regexp::Token::CharClass::POSIX"
"PPIx::Regexp::Token::CharClass::POSIX::Unknown"
"PPIx::Regexp::Token::CharClass::Simple" "PPIx::Regexp::Token::Code"
"PPIx::Regexp::Token::Comment" "PPIx::Regexp::Token::Condition"
"PPIx::Regexp::Token::Control" "PPIx::Regexp::Token::Delimiter"
"PPIx::Regexp::Token::Greediness" "PPIx::Regexp::Token::GroupType"
"PPIx::Regexp::Token::GroupType::Assertion"
"PPIx::Regexp::Token::GroupType::BranchReset"
"PPIx::Regexp::Token::GroupType::Code"
"PPIx::Regexp::Token::GroupType::Modifier"
"PPIx::Regexp::Token::GroupType::NamedCapture"
"PPIx::Regexp::Token::GroupType::Subexpression"
"PPIx::Regexp::Token::GroupType::Switch"
"PPIx::Regexp::Token::Interpolation" "PPIx::Regexp::Token::Literal"
"PPIx::Regexp::Token::Modifier" "PPIx::Regexp::Token::Operator"
"PPIx::Regexp::Token::Quantifier" "PPIx::Regexp::Token::Recursion"
"PPIx::Regexp::Token::Reference" "PPIx::Regexp::Token::Structure"
"PPIx::Regexp::Token::Unknown" "PPIx::Regexp::Token::Unmatched"
"PPIx::Regexp::Token::Whitespace" "PPIx::Regexp::Tokenizer"
"PPIx::Regexp::Util" "PPIx::Utilities" "PPIx::Utilities::Exception::Bug"
"PPIx::Utilities::Node" "PPIx::Utilities::Statement" "PPM::Repositories"
"Package::Constants" "Package::DeprecationManager" "Package::Stash"
"Package::Stash::Conflicts" "Package::Stash::PP" "Package::Stash::XS"
"Params::Check" "Params::Util" "Parse::CPAN::Meta" "Perl::Critic"
"Perl::Critic::Annotation" "Perl::Critic::CORE_DEVELOPER"
"Perl::Critic::Command" "Perl::Critic::Config" "Perl::Critic::DEVELOPER"
"Perl::Critic::Document" "Perl::Critic::Exception"
"Perl::Critic::Exception::AggregateConfiguration"
"Perl::Critic::Exception::Configuration"
"Perl::Critic::Exception::Configuration::Generic"
"Perl::Critic::Exception::Configuration::NonExistentPolicy"
"Perl::Critic::Exception::Configuration::Option"
"Perl::Critic::Exception::Configuration::Option::Global"
"Perl::Critic::Exception::Configuration::Option::Global::ExtraParameter"
"Perl::Critic::Exception::Configuration::Option::Global::ParameterValue"
"Perl::Critic::Exception::Configuration::Option::Policy"
"Perl::Critic::Exception::Configuration::Option::Policy::ExtraParameter"
"Perl::Critic::Exception::Configuration::Option::Policy::ParameterValue"
"Perl::Critic::Exception::Fatal" "Perl::Critic::Exception::Fatal::Generic"
"Perl::Critic::Exception::Fatal::Internal"
"Perl::Critic::Exception::Fatal::PolicyDefinition"
"Perl::Critic::Exception::IO" "Perl::Critic::Exception::Parse"
"Perl::Critic::OptionsProcessor" "Perl::Critic::Policy"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitBooleanGrep"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitComplexMappings"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitLvalueSubstr"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitReverseSortBlock"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitSleepViaSelect"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitStringyEval"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitStringySplit"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitUniversalCan"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitUniversalIsa"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitVoidGrep"
"Perl::Critic::Policy::BuiltinFunctions::ProhibitVoidMap"
"Perl::Critic::Policy::BuiltinFunctions::RequireBlockGrep"
"Perl::Critic::Policy::BuiltinFunctions::RequireBlockMap"
"Perl::Critic::Policy::BuiltinFunctions::RequireGlobFunction"
"Perl::Critic::Policy::BuiltinFunctions::RequireSimpleSortBlock"
"Perl::Critic::Policy::ClassHierarchies::ProhibitAutoloading"
"Perl::Critic::Policy::ClassHierarchies::ProhibitExplicitISA"
"Perl::Critic::Policy::ClassHierarchies::ProhibitOneArgBless"
"Perl::Critic::Policy::CodeLayout::ProhibitHardTabs"
"Perl::Critic::Policy::CodeLayout::ProhibitParensWithBuiltins"
"Perl::Critic::Policy::CodeLayout::ProhibitQuotedWordLists"
"Perl::Critic::Policy::CodeLayout::ProhibitTrailingWhitespace"
"Perl::Critic::Policy::CodeLayout::RequireConsistentNewlines"
"Perl::Critic::Policy::CodeLayout::RequireTidyCode"
"Perl::Critic::Policy::CodeLayout::RequireTrailingCommas"
"Perl::Critic::Policy::ControlStructures::ProhibitCStyleForLoops"
"Perl::Critic::Policy::ControlStructures::ProhibitCascadingIfElse"
"Perl::Critic::Policy::ControlStructures::ProhibitDeepNests"
"Perl::Critic::Policy::ControlStructures::ProhibitLabelsWithSpecialBlockNam
es"
"Perl::Critic::Policy::ControlStructures::ProhibitMutatingListFunctions"
"Perl::Critic::Policy::ControlStructures::ProhibitNegativeExpressionsInUnle
ssAndUntilConditions"
"Perl::Critic::Policy::ControlStructures::ProhibitPostfixControls"
"Perl::Critic::Policy::ControlStructures::ProhibitUnlessBlocks"
"Perl::Critic::Policy::ControlStructures::ProhibitUnreachableCode"
"Perl::Critic::Policy::ControlStructures::ProhibitUntilBlocks"
"Perl::Critic::Policy::Documentation::PodSpelling"
"Perl::Critic::Policy::Documentation::RequirePackageMatchesPodName"
"Perl::Critic::Policy::Documentation::RequirePodAtEnd"
"Perl::Critic::Policy::Documentation::RequirePodLinksIncludeText"
"Perl::Critic::Policy::Documentation::RequirePodSections"
"Perl::Critic::Policy::ErrorHandling::RequireCarping"
"Perl::Critic::Policy::ErrorHandling::RequireCheckingReturnValueOfEval"
"Perl::Critic::Policy::InputOutput::ProhibitBacktickOperators"
"Perl::Critic::Policy::InputOutput::ProhibitBarewordFileHandles"
"Perl::Critic::Policy::InputOutput::ProhibitExplicitStdin"
"Perl::Critic::Policy::InputOutput::ProhibitInteractiveTest"
"Perl::Critic::Policy::InputOutput::ProhibitJoinedReadline"
"Perl::Critic::Policy::InputOutput::ProhibitOneArgSelect"
"Perl::Critic::Policy::InputOutput::ProhibitReadlineInForLoop"
"Perl::Critic::Policy::InputOutput::ProhibitTwoArgOpen"
"Perl::Critic::Policy::InputOutput::RequireBracedFileHandleWithPrint"
"Perl::Critic::Policy::InputOutput::RequireBriefOpen"
"Perl::Critic::Policy::InputOutput::RequireCheckedClose"
"Perl::Critic::Policy::InputOutput::RequireCheckedOpen"
"Perl::Critic::Policy::InputOutput::RequireCheckedSyscalls"
"Perl::Critic::Policy::InputOutput::RequireEncodingWithUTF8Layer"
"Perl::Critic::Policy::Miscellanea::ProhibitFormats"
"Perl::Critic::Policy::Miscellanea::ProhibitTies"
"Perl::Critic::Policy::Miscellanea::ProhibitUnrestrictedNoCritic"
"Perl::Critic::Policy::Miscellanea::ProhibitUselessNoCritic"
"Perl::Critic::Policy::Miscellanea::RequireRcsKeywords"
"Perl::Critic::Policy::Modules::ProhibitAutomaticExportation"
"Perl::Critic::Policy::Modules::ProhibitConditionalUseStatements"
"Perl::Critic::Policy::Modules::ProhibitEvilModules"
"Perl::Critic::Policy::Modules::ProhibitExcessMainComplexity"
"Perl::Critic::Policy::Modules::ProhibitMultiplePackages"
"Perl::Critic::Policy::Modules::RequireBarewordIncludes"
"Perl::Critic::Policy::Modules::RequireEndWithOne"
"Perl::Critic::Policy::Modules::RequireExplicitPackage"
"Perl::Critic::Policy::Modules::RequireFilenameMatchesPackage"
"Perl::Critic::Policy::Modules::RequireNoMatchVarsWithUseEnglish"
"Perl::Critic::Policy::Modules::RequireVersionVar"
"Perl::Critic::Policy::NamingConventions::Capitalization"
"Perl::Critic::Policy::NamingConventions::ProhibitAmbiguousNames"
"Perl::Critic::Policy::Objects::ProhibitIndirectSyntax"
"Perl::Critic::Policy::References::ProhibitDoubleSigils"
"Perl::Critic::Policy::RegularExpressions::ProhibitCaptureWithoutTest"
"Perl::Critic::Policy::RegularExpressions::ProhibitComplexRegexes"
"Perl::Critic::Policy::RegularExpressions::ProhibitEnumeratedClasses"
"Perl::Critic::Policy::RegularExpressions::ProhibitEscapedMetacharacters"
"Perl::Critic::Policy::RegularExpressions::ProhibitFixedStringMatches"
"Perl::Critic::Policy::RegularExpressions::ProhibitSingleCharAlternation"
"Perl::Critic::Policy::RegularExpressions::ProhibitUnusedCapture"
"Perl::Critic::Policy::RegularExpressions::ProhibitUnusualDelimiters"
"Perl::Critic::Policy::RegularExpressions::RequireBracesForMultiline"
"Perl::Critic::Policy::RegularExpressions::RequireDotMatchAnything"
"Perl::Critic::Policy::RegularExpressions::RequireExtendedFormatting"
"Perl::Critic::Policy::RegularExpressions::RequireLineBoundaryMatching"
"Perl::Critic::Policy::Subroutines::ProhibitAmpersandSigils"
"Perl::Critic::Policy::Subroutines::ProhibitBuiltinHomonyms"
"Perl::Critic::Policy::Subroutines::ProhibitExcessComplexity"
"Perl::Critic::Policy::Subroutines::ProhibitExplicitReturnUndef"
"Perl::Critic::Policy::Subroutines::ProhibitManyArgs"
"Perl::Critic::Policy::Subroutines::ProhibitNestedSubs"
"Perl::Critic::Policy::Subroutines::ProhibitReturnSort"
"Perl::Critic::Policy::Subroutines::ProhibitSubroutinePrototypes"
"Perl::Critic::Policy::Subroutines::ProhibitUnusedPrivateSubroutines"
"Perl::Critic::Policy::Subroutines::ProtectPrivateSubs"
"Perl::Critic::Policy::Subroutines::RequireArgUnpacking"
"Perl::Critic::Policy::Subroutines::RequireFinalReturn"
"Perl::Critic::Policy::TestingAndDebugging::ProhibitNoStrict"
"Perl::Critic::Policy::TestingAndDebugging::ProhibitNoWarnings"
"Perl::Critic::Policy::TestingAndDebugging::ProhibitProlongedStrictureOverr
ide" "Perl::Critic::Policy::TestingAndDebugging::RequireTestLabels"
"Perl::Critic::Policy::TestingAndDebugging::RequireUseStrict"
"Perl::Critic::Policy::TestingAndDebugging::RequireUseWarnings"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitCommaSeparatedStatemen
ts" "Perl::Critic::Policy::ValuesAndExpressions::ProhibitComplexVersion"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitConstantPragma"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitEmptyQuotes"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitEscapedCharacters"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitImplicitNewlines"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiteral
s" "Perl::Critic::Policy::ValuesAndExpressions::ProhibitLeadingZeros"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitLongChainsOfMethodCall
s" "Perl::Critic::Policy::ValuesAndExpressions::ProhibitMagicNumbers"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitMismatchedOperators"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitMixedBooleanOperators"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitNoisyQuotes"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitQuotesAsQuotelikeOpera
torDelimiters"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitSpecialLiteralHeredocT
erminator"
"Perl::Critic::Policy::ValuesAndExpressions::ProhibitVersionStrings"
"Perl::Critic::Policy::ValuesAndExpressions::RequireConstantVersion"
"Perl::Critic::Policy::ValuesAndExpressions::RequireInterpolationOfMetachar
s" "Perl::Critic::Policy::ValuesAndExpressions::RequireNumberSeparators"
"Perl::Critic::Policy::ValuesAndExpressions::RequireQuotedHeredocTerminator
"
"Perl::Critic::Policy::ValuesAndExpressions::RequireUpperCaseHeredocTermina
tor" "Perl::Critic::Policy::Variables::ProhibitConditionalDeclarations"
"Perl::Critic::Policy::Variables::ProhibitEvilVariables"
"Perl::Critic::Policy::Variables::ProhibitLocalVars"
"Perl::Critic::Policy::Variables::ProhibitMatchVars"
"Perl::Critic::Policy::Variables::ProhibitPackageVars"
"Perl::Critic::Policy::Variables::ProhibitPerl4PackageNames"
"Perl::Critic::Policy::Variables::ProhibitPunctuationVars"
"Perl::Critic::Policy::Variables::ProhibitReusedNames"
"Perl::Critic::Policy::Variables::ProhibitUnusedVariables"
"Perl::Critic::Policy::Variables::ProtectPrivateVars"
"Perl::Critic::Policy::Variables::RequireInitializationForLocalVars"
"Perl::Critic::Policy::Variables::RequireLexicalLoopIterators"
"Perl::Critic::Policy::Variables::RequireLocalizedPunctuationVars"
"Perl::Critic::Policy::Variables::RequireNegativeIndices"
"Perl::Critic::PolicyConfig" "Perl::Critic::PolicyFactory"
"Perl::Critic::PolicyListing" "Perl::Critic::PolicyParameter"
"Perl::Critic::PolicyParameter::Behavior"
"Perl::Critic::PolicyParameter::Behavior::Boolean"
"Perl::Critic::PolicyParameter::Behavior::Enumeration"
"Perl::Critic::PolicyParameter::Behavior::Integer"
"Perl::Critic::PolicyParameter::Behavior::String"
"Perl::Critic::PolicyParameter::Behavior::StringList"
"Perl::Critic::PolicySummary" "Perl::Critic::ProfilePrototype"
"Perl::Critic::Statistics" "Perl::Critic::TestUtils" "Perl::Critic::Theme"
"Perl::Critic::ThemeListing" "Perl::Critic::UserProfile"
"Perl::Critic::Utils" "Perl::Critic::Utils::Constants"
"Perl::Critic::Utils::DataConversion" "Perl::Critic::Utils::McCabe"
"Perl::Critic::Utils::POD"
"Perl::Critic::Utils::POD::ParseInteriorSequence"
"Perl::Critic::Utils::PPI" "Perl::Critic::Utils::Perl"
"Perl::Critic::Violation" "Perl::OSType" "Perl::TODO" "PerlEx::DBI"
"PerlEx::Example::spell" "PerlEx::SOAP" "PerlEx::XMLRPC" "PerlIO"
"PerlIO::encoding" "PerlIO::scalar" "PerlIO::via"
"PerlIO::via::QuotedPrint" "Pod::Checker" "Pod::Escapes" "Pod::Find"
"Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX" "Pod::Man"
"Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::PerlEz"
"Pod::Perldoc" "Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO"
"Pod::Perldoc::ToChecker" "Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff"
"Pod::Perldoc::ToPod" "Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText"
"Pod::Perldoc::ToTk" "Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Select"
"Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "Readonly"
"Readonly::XS" "SDBM_File" "SQL::Dialects::ANSI" "SQL::Dialects::AnyData"
"SQL::Dialects::CSV" "SQL::Dialects::Role" "SQL::Eval" "SQL::Parser"
"SQL::Statement" "SQL::Statement::Embed" "SQL::Statement::Function"
"SQL::Statement::Functions" "SQL::Statement::GetInfo"
"SQL::Statement::Operation" "SQL::Statement::Placeholder"
"SQL::Statement::RAM" "SQL::Statement::Roadmap" "SQL::Statement::Structure"
"SQL::Statement::Syntax" "SQL::Statement::Term"
"SQL::Statement::TermFactory" "SQL::Statement::Util" "Safe" "Scalar::Util"
"Scalar::Util::PP" "Scope::Guard" "Search::Dict" "SelectSaver" "SelfLoader"
"Shell" "Shell::Command" "Socket" "Storable" "Sub::Exporter"
"Sub::Exporter::Cookbook" "Sub::Exporter::Tutorial" "Sub::Exporter::Util"
"Sub::Install" "Sub::Name" "Sub::Uplevel" "Symbol" "Sys::Hostname"
"Sys::Syslog" "Sys::Syslog::Win32" "TAP::Base" "TAP::Formatter::Base"
"TAP::Formatter::Color" "TAP::Formatter::Console"
"TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Harness::Beyond" "TAP::Object" "TAP::Parser"
"TAP::Parser::Aggregator" "TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::SourceHandler"
"TAP::Parser::SourceHandler::Executable" "TAP::Parser::SourceHandler::File"
"TAP::Parser::SourceHandler::Handle" "TAP::Parser::SourceHandler::Perl"
"TAP::Parser::SourceHandler::RawTAP" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer"
"Task::Weaken" "Tcl" "Tcl::tkkit" "Term::ANSIColor" "Term::Cap"
"Term::Complete" "Term::ReadKey" "Term::ReadLine" "Term::ReadLine::Perl"
"Term::ReadLine::readline" "Term::UI" "Term::UI::History" "Test"
"Test::Builder" "Test::Builder::IO::Scalar" "Test::Builder::Module"
"Test::Builder::Tester" "Test::Builder::Tester::Color" "Test::Differences"
"Test::Exception" "Test::Harness" "Test::Moose" "Test::More"
"Test::Perl::Critic::Policy" "Test::Simple" "Test::Tutorial" "Text::Abbrev"
"Text::Autoformat" "Text::Balanced" "Text::CSV_XS" "Text::Diff"
"Text::Diff::Config" "Text::Diff::Table" "Text::Glob" "Text::ParseWords"
"Text::Reform" "Text::Soundex" "Text::Tabs" "Text::Wrap" "Thread"
"Thread::Queue" "Thread::Semaphore" "Tie::Array" "Tie::File" "Tie::Handle"
"Tie::Hash" "Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash"
"Tie::Registry" "Tie::Scalar" "Tie::StdHandle" "Tie::SubstrHash"
"Time::HiRes" "Time::Local" "Time::Piece" "Time::Seconds" "Time::gmtime"
"Time::localtime" "Time::tm" "Tkx" "Tkx::LabEntry" "Tkx::MegaConfig"
"Tkx::Tutorial" "Try::Tiny" "UNIVERSAL" "URI" "URI::Escape"
"URI::Heuristic" "URI::IRI" "URI::QueryParam" "URI::Split" "URI::URL"
"URI::WithBase" "URI::_foreign" "URI::_generic" "URI::_idna" "URI::_ldap"
"URI::_login" "URI::_punycode" "URI::_query" "URI::_segment" "URI::_server"
"URI::_userpass" "URI::data" "URI::file" "URI::file::Base" "URI::file::FAT"
"URI::file::Mac" "URI::file::OS2" "URI::file::QNX" "URI::file::Unix"
"URI::file::Win32" "URI::ftp" "URI::gopher" "URI::http" "URI::https"
"URI::ldap" "URI::ldapi" "URI::ldaps" "URI::mailto" "URI::mms" "URI::news"
"URI::nntp" "URI::pop" "URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu"
"URI::sip" "URI::sips" "URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270"
"URI::urn" "URI::urn::isbn" "URI::urn::oid" "Unicode::Collate"
"Unicode::Collate::CJK::Big5" "Unicode::Collate::CJK::GB2312"
"Unicode::Collate::CJK::JISX0208" "Unicode::Collate::CJK::Korean"
"Unicode::Collate::CJK::Pinyin" "Unicode::Collate::CJK::Stroke"
"Unicode::Collate::Locale" "Unicode::Normalize" "Unicode::UCD"
"User::grent" "User::pwent" "WWW::Mechanize" "WWW::Mechanize::Cookbook"
"WWW::Mechanize::Examples" "WWW::Mechanize::FAQ" "WWW::Mechanize::Image"
"WWW::Mechanize::Link" "WWW::RobotRules" "WWW::RobotRules::AnyDBM_File"
"Win32" "Win32::API" "Win32::API::Callback" "Win32::API::Struct"
"Win32::API::Test" "Win32::API::Type" "Win32::AuthenticateUser"
"Win32::ChangeNotify" "Win32::Clipboard" "Win32::Console"
"Win32::Console::ANSI" "Win32::DBIODBC" "Win32::Event" "Win32::EventLog"
"Win32::File" "Win32::FileSecurity" "Win32::IPC" "Win32::Internet"
"Win32::Job" "Win32::Mutex" "Win32::NetAdmin" "Win32::NetResource"
"Win32::ODBC" "Win32::OLE" "Win32::OLE::Const" "Win32::OLE::Enum"
"Win32::OLE::Lite" "Win32::OLE::NEWS" "Win32::OLE::NLS" "Win32::OLE::TPJ"
"Win32::OLE::TypeInfo" "Win32::OLE::Variant" "Win32::PerfLib" "Win32::Pipe"
"Win32::Process" "Win32::Registry" "Win32::Semaphore" "Win32::Service"
"Win32::Shortcut" "Win32::Sound" "Win32::TieRegistry" "Win32::WinError"
"Win32API::File" "Win32API::Net" "Win32API::Registry" "Win32CORE"
"XML::Parser" "XML::Parser::Expat" "XML::Parser::Style::Debug"
"XML::Parser::Style::Objects" "XML::Parser::Style::Stream"
"XML::Parser::Style::Subs" "XML::Parser::Style::Tree" "XML::Simple"
"XML::Simple::FAQ" "XSLoader" "YAML::LibYAML" "YAML::XS"
"YAML::XS::LibYAML" "attributes" "auto::DBD::Oracle::mk" "autodie"
"autodie::exception" "autodie::exception::system" "autodie::hints"
"autouse" "base" "bigint" "bignum" "bigrat" "blib" "bytes" "charnames"
"constant" "deprecate" "diagnostics" "encoding" "encoding::warnings"
"feature" "fields" "filetest" "if" "inc::latest" "inc::latest::private"
"integer" "less" "lib" "locale" "lwpcook" "lwptut" "metaclass" "mro"
"mylib" "oose" "open.pod" "ops" "overload" "overload::numbers"
"overloading" "parent" "perllocal" "pods::a2p" "pods::activeperl"
"pods::activeperl-changes" "pods::activeperl-release" "pods::perl"
"pods::perl5004delta" "pods::perl5005delta" "pods::perl5100delta"
"pods::perl5101delta" "pods::perl5110delta" "pods::perl5111delta"
"pods::perl5112delta" "pods::perl5113delta" "pods::perl5114delta"
"pods::perl5115delta" "pods::perl5120delta" "pods::perl5121delta"
"pods::perl5122delta" "pods::perl5123delta" "pods::perl5130delta"
"pods::perl51310delta" "pods::perl51311delta" "pods::perl5131delta"
"pods::perl5132delta" "pods::perl5133delta" "pods::perl5134delta"
"pods::perl5135delta" "pods::perl5136delta" "pods::perl5137delta"
"pods::perl5138delta" "pods::perl5139delta" "pods::perl5140delta"
"pods::perl5141delta" "pods::perl5142delta" "pods::perl561delta"
"pods::perl56delta" "pods::perl570delta" "pods::perl571delta"
"pods::perl572delta" "pods::perl573delta" "pods::perl581delta"
"pods::perl582delta" "pods::perl583delta" "pods::perl584delta"
"pods::perl585delta" "pods::perl586delta" "pods::perl587delta"
"pods::perl588delta" "pods::perl589delta" "pods::perl58delta"
"pods::perl590delta" "pods::perl591delta" "pods::perl592delta"
"pods::perl593delta" "pods::perl594delta" "pods::perl595delta"
"pods::perlaix" "pods::perlamiga" "pods::perlapi" "pods::perlapio"
"pods::perlartistic" "pods::perlbeos" "pods::perlbook" "pods::perlboot"
"pods::perlbot" "pods::perlbs2000" "pods::perlcall" "pods::perlce"
"pods::perlcheat" "pods::perlclib" "pods::perlcn" "pods::perlcommunity"
"pods::perlcompile" "pods::perlcygwin" "pods::perldata"
"pods::perldbmfilter" "pods::perldebguts" "pods::perldebtut"
"pods::perldebug" "pods::perldelta" "pods::perldgux" "pods::perldiag"
"pods::perldoc" "pods::perldos" "pods::perldsc" "pods::perlebcdic"
"pods::perlembed" "pods::perlepoc" "pods::perlfaq" "pods::perlfaq1"
"pods::perlfaq2" "pods::perlfaq3" "pods::perlfaq4" "pods::perlfaq5"
"pods::perlfaq6" "pods::perlfaq7" "pods::perlfaq8" "pods::perlfaq9"
"pods::perlfilter" "pods::perlfork" "pods::perlform" "pods::perlfreebsd"
"pods::perlfunc" "pods::perlgit" "pods::perlglossary" "pods::perlgpl"
"pods::perlguts" "pods::perlhack" "pods::perlhacktips" "pods::perlhacktut"
"pods::perlhaiku" "pods::perlhist" "pods::perlhpux" "pods::perlhurd"
"pods::perlintern" "pods::perlinterp" "pods::perlintro" "pods::perliol"
"pods::perlipc" "pods::perlirix" "pods::perljp" "pods::perlko"
"pods::perllexwarn" "pods::perllinux" "pods::perllocale" "pods::perllol"
"pods::perlmacos" "pods::perlmacosx" "pods::perlmod" "pods::perlmodinstall"
"pods::perlmodlib" "pods::perlmodstyle" "pods::perlmpeix"
"pods::perlmroapi" "pods::perlnetware" "pods::perlnewmod"
"pods::perlnumber" "pods::perlobj" "pods::perlop" "pods::perlopenbsd"
"pods::perlopentut" "pods::perlos2" "pods::perlos390" "pods::perlos400"
"pods::perlpacktut" "pods::perlperf" "pods::perlplan9" "pods::perlpod"
"pods::perlpodspec" "pods::perlpodstyle" "pods::perlpolicy"
"pods::perlport" "pods::perlpragma" "pods::perlqnx" "pods::perlre"
"pods::perlreapi" "pods::perlrebackslash" "pods::perlrecharclass"
"pods::perlref" "pods::perlreftut" "pods::perlreguts" "pods::perlrequick"
"pods::perlreref" "pods::perlretut" "pods::perlriscos" "pods::perlrun"
"pods::perlsec" "pods::perlsolaris" "pods::perlsource" "pods::perlstyle"
"pods::perlsub" "pods::perlsymbian" "pods::perlsyn" "pods::perlthrtut"
"pods::perltie" "pods::perltoc" "pods::perltodo" "pods::perltooc"
"pods::perltoot" "pods::perltrap" "pods::perltru64" "pods::perltw"
"pods::perlunicode" "pods::perlunifaq" "pods::perluniintro"
"pods::perluniprops" "pods::perlunitut" "pods::perlutil" "pods::perluts"
"pods::perlvar" "pods::perlvmesa" "pods::perlvms" "pods::perlvos"
"pods::perlwin32" "pods::perlxs" "pods::perlxstut" "re" "sigtrap"
"sort.pod" "strict" "subs" "threads" "threads::shared" "utf8" "vars"
"version" "version::Internals" "version::Requirements" "version::vxs"
"vmsish" "warnings" "warnings::register"))
