# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Expect
version:      1.20
version_from: Expect.pm
installdirs:  site
requires:
    IO::Pty:                       1.03
    IO::Tty:                       1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
