#!/bin/bash

if [ $# != 2 ]; then
    cat <<EOF 
Usage: 
$ $(basename $0) {n} {text}

The list of possible values for {n}
0: Find this C symbol
1: Find this definition
2: Find functions called by this function
3: Find functions calling this function
4: Find this text string
6: Find this egrep pattern
7: Find this file
8: Find files #including this file
9: Find places where this symbol is assigned a value
EOF
    exit 1
fi

search_up() {
    local look=${PWD%/}
    while [[ -n $look ]]; do
        [[ -e $look/$1 ]] && {
            printf '%s\n' "$look"
            return
        }
        look=${look%/*}
    done
    [[ -e /$1 ]] && echo /
}

SEARCH=$(search_up "cscope.out")
if [ -n "$SEARCH" ]; then
    TAG_FILE="$SEARCH/cscope.out"
else
    TAG_FILE="~/.emacs.d/tags/cscope.out"
fi
    
echo "Use: $TAG_FILE"
cscope -d -f $TAG_FILE -R -L${1} ${2}
