#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: `basename $0` <1.deb>"
    exit 1
fi

## apt install binutils
## ar x {file.deb}
use_ar() {
    data=$(ar t "$1" | grep data.tar)
    ar p "$1" $data | tar xfvJ -
}

## dpkg -c {file.deb}
use_dpkg() {
    dpkg-deb -xv "$1" .
}

use_ar $@
