#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: `basename $0` <1.deb>"
    exit 1
fi


## sudo apt install binutils
## ar x {file.deb}
use_ar() {
    ar p "$1" $(ar t "$1" | grep data.tar) | tar xfvJ -
}

## dpkg -c {file.deb}
use_dpkg() {
    dpkg-deb -xv "$1" .
}

use_ar $@
