#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: `basename $0` <1.deb>"
    exit 1
fi


## sudo apt install binutils
use_ar() {
    ar vx "$1"
    tar xf data.tar.*
    rm -f data.tar.* control.tar.*
}


use_dpkg() {
    dpkg-deb -xv "$1" .
}

use_dpkg $@
