#!/bin/bash

echo "Docker rm exit clean"

ps_list=$(docker ps -a | grep Exit)
if [ -n "$ps_list" ]; then
    echo $ps_list | cut -d ' ' -f 1 | xargs docker rm
else
    echo "Docker ps is already clean"
fi

echo "Docker rm exit done"
