#!/bin/bash

echo "Docker images clean ..."
img_list=$(docker images --filter "dangling=true" -q --no-trunc)
if [ -n "$img_list" ]; then
    docker rmi $img_list
else
    echo "Docker images already cleaned"
fi

echo "Docker images clean done"
