#!/bin/bash

echo "Clean Docker images ..."
img_list=$(docker images --filter "dangling=true" -q --no-trunc)
if [ -n "$img_list" ]; then
    docker rmi $img_list
else
    echo "Images already cleaned"
fi

echo "Clean Docker images done"
