#!/bin/bash

emacs_service() {
    local target=.config/systemd/user/emacs.service
    tee $target <<EOF
[Unit]
Description=Emacs text editor
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Environment=SSH_AUTH_SOCK=%t/keyring/ssh
Restart=on-failure

[Install]
WantedBy=default.target
EOF

    echo "Daemon reload"
    systemctl daemon-reload --user
    echo "Service start"
    systemctl start --user emacs
}

emacs_service

echo "emacs service done"
