#!/bin/bash

if [ -z $(command -v evolution) ] ; then
    echo "Cannot find evolution"
    exit 1
fi

force_down() {
    echo "evolution down"
    evolution --force-shutdown > /dev/null 2>&1
    sleep 2s
}

force_down

echo "evolution force down done"
