#!/bin/bash

if [ -z $(command -v evolution) ] ; then
    echo "Cannot find evolution"
    exit 1
fi

disable_alarm() {
    echo "kill evolution-alarm-notify"
    sudo killall evolution-alarm
    echo "chmod -x evolution-alarm-notify"
    sudo chmod -x /usr/libexec/evolution-data-server/evolution-alarm-notify
}

disable_alarm

echo "evolution disble evolution-alarm-notify done"
