#!/bin/bash

if [ -z $(command -v evolution) ] ; then
    echo "Cannot find evolution"
    exit 1
fi

force_down() {
    echo "evolution down"
    evolution --force-shutdown > /dev/null 2>&1
    sleep 2s
}

disable_alarm() {
    local file=/usr/libexec/evolution-data-server/evolution-alarm-notify
    echo "evolution noalarm"
    echo "kill evolution-alarm-notify"
    sudo killall evolution-alarm
    if [ -f $file ]; then
        echo "chmod -x $file"
        sudo chmod -x $file
    else
        echo "Cannot find $file"
    fi
}

case $1 in
    force )
        force_down
        ;;
    noalarm )
        disable_alarm
        ;;

    * )
        echo "Usage: $(basename $0) {force|noalarm}"
        ;;
esac
