#!/usr/bin/env python

### Script main entry

import os
import sys

coredirname="ffmpeg-core"

def main():
    ## add for import path
    srcdir = os.path.dirname(os.path.realpath(__file__))
    srcdir = srcdir.replace("\\", "/")
    sys.path.append(srcdir + "/../lib/python/okapi")

    import utils.common as common
    import framework.dispatch as dispatch

    common.setcoredir(coredirname)
    workdir = common.getworkdir()
    print "Work directory: %s" % (workdir)

    dispatcher = dispatch.Dispatch(workdir, srcdir, sys.argv);
    dispatcher.run()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print "\nUser Press Ctrl+C, exit\n"
