#!/usr/bin/env python3

#-*- coding:utf-8 -*-

import os
import sys
import time
import re

def get_time_stamp():
    ct = time.time()
    local_time = time.localtime(ct)
    data_head = time.strftime("%Y-%m-%d-%H-%M-%S", local_time)
    return data_head

tmp_file = "/tmp/" + get_time_stamp() + ".log"
os.system("whoami > " + tmp_file)
fp = open(tmp_file)
user_name = fp.read()
fp.close()
os.remove(tmp_file)
tmp_file =  "/tmp/" + user_name[:-1] +"-"+ tmp_file[5:]

if (os.system("git log > " + tmp_file) != 0):
    print("\033[31m")
    print("The current directory does not have a Git directory!")
    print("Change the directory and try again")
    print("\033[37m")
    exit(0)

fp = open(tmp_file)
lines = fp.readlines()
fp.close()

line_num = 1
result = []
fp = open(tmp_file,"w")
for line in lines[::-1]:
    if re.match(r'^commit', line):
        line = "\033[33m" + line[:-1] + "\033[31m  -gr"+str(line_num) + "\n"
        line_num += 1
    elif re.match(r'^Author', line):
        line = "\033[32m" + line
    elif re.match(r'^Date', line):
        line = "\033[34m" + line
    else:
        line = "\033[37m" + line
    result.append(line)
result.reverse()
for i in result:
    fp.write(i)
fp.close()
os.system("more " + tmp_file) 

os.remove(tmp_file)

print ("\033[37m")
exit(1)
