#!/bin/bash

JENKINS_BROWSER=${JENKINS_BROWSER:-google-chrome}
JENKINS_URL=${JENKINS_URL:-http://localhost:8080/}
JENKINS_CLI=${JENKINS_CLI:-/opt/jenkins/cli/jenkins-cli.jar}
JENKINS_AUTH=${JENKINS_AUTH:-admin:admin}

open() {
    echo "jenkins open"
    exec $JENKINS_BROWSER $JENKINS_URL
}

cli() {
    java -jar $JENKINS_CLI -s $JENKINS_URL -webSocket -auth $JENKINS_AUTH $*
}

case $1 in
    open )
        open
        ;;
    cli )
        shift
        cli $*
        ;;
    * )
        echo "$(basename $0) {open|cli}"
        ;;
esac
