#!/bin/bash

pplist=$(ps -A -ostat,ppid | awk '/[zZ]/{ print $2 }')
if [ -n "$pplist" ]; then
    kill -9 $pplist
    echo "Kill zombie's ppids."
    echo "$pplist"
else
    echo "No zombie process found"
fi    
