#!/usr/bin/expect -f

##http://expect.sourceforge.net/
##http://en.wikipedia.org/wiki/Expect

##sudo apt install expect
##sudo yum install expect

if {$argc < 2} {
    puts stderr "Usage: $argv0 <passwd> <from> <to>"
    exit 1
}

set timeout 0
set passwd [lindex $argv 0]
set from   [lindex $argv 1]
set to     [lindex $argv 2]

spawn scp -o "StrictHostKeyChecking no" -r $from $to
expect "${from}'s password:"
exec sleep 1
send "${passwd}\n"
interact
