#!/bin/bash

## x11vnc
#set -x -v

vnc_passwd=password
vnc_pw_file=~/.vnc/passwd

install_service() {
    echo -n "Please input x11-vnc Password: "
    read -s vnc_passwd
    
    sudo tee /lib/systemd/system/x11vnc.service <<EOF
[Unit]
Description=x11vnc service
After=display-manager.service network.target syslog.target

[Service]
Type=simple
ExecStart=/usr/bin/x11vnc -forever -display :0 -auth guess -passwd $vnc_passwd
ExecStop=/usr/bin/killall x11vnc
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl enable x11vnc.service
    sudo systemctl start x11vnc.service
    
    echo "install service done"
}

remove_service() {
    sudo systemctl stop x11vnc.service
    sudo systemctl disable x11vnc.service
    sudo rm /lib/systemd/system/x11vnc.service

    echo "remove service done"
}

install_timezone () {
    TZ=Asia/Shanghai
    sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    sudo echo $TZ > /etc/timezone

    echo "install timezone done"
}

install_deps() {
    if [ -z "$(pidof x11vnc)" ]; then
        sudo apt install -y x11vnc xvfb net-tools
    fi

    echo "install deps done"
}

start() {
    if [ -z "$(pidof x11vnc)" ]; then
        if [ -f $vnc_pw_file ]; then
            echo "use exist $vnc_pw_file"
        else
            echo -n Please input VNC password: 
            read -s vnc_passwd
            mkdir ~/.vnc
            x11vnc -storepasswd $vnc_passwd $vnc_pw_file
        fi

        echo "staring x11vnc in backgroud"
        x11vnc -ncache 10 -forever -usepw -create
        sleep 5s
    else
        echo "x11vnc already exist."
    fi

    echo "start done"
}

stop () {
    if [ -z "$(pidof x11vnc)" ]; then
        echo "no x11vnc exist"
    else
        killall x11vnc
    fi

    echo "stop done"
}

status () {
    ps -ef | grep x11vnc | grep -v grep
}

case "$1" in
    "install" )
        install_service
        ;;
    "remove" )
        remove_service
        ;;
    "deps" )
        install_deps
        ;;
    "start" )
        start
        ;;
    "stop" )
        stop
        ;;
    "status" )
        status
        ;;
    * )
        echo "$(basename $0) [install|remove|deps|start|stop|status]"
        ;;
esac
