#!/bin/bash

## https://github.com/garyparrot/rofi-translate
## https://github.com/soimort/translate-shell

online() {
    gawk -f <(curl -Ls --compressed https://git.io/translate) -- -shell
}

offline() {
    trans --shell
}

offline

echo "trans shell done ..."
