#! /bin/sh

if [ $# = 0 ]; then
    echo "Usage: $(basename $0) {files|dirs}"
    exit 0
fi

for i in $@ ; do
    if [ -d $i ]; then
        vlc -I "dummy" --novideo --play-and-exit $i/*
    else
        vlc -I "dummy" --novideo --play-and-exit $i
    fi
done

echo "vlca done"
