#! /bin/sh

if [ $# = 0 ]; then
    echo "Usage: $(basename $0) {files|dirs}"
    exit 0
fi

vlca_play() {
    local vca_cmd="vlc -I dummy --novideo --play-and-exit"
    for i in "$@" ; do
        if [ -d "$i" ]; then
            $vca_cmd "$i"/*
        else
            $vca_cmd "$i"
        fi
    done
}

vlca_play "$@"

echo "vlca done"
