language: emacs-lisp

# See https://github.com/flycheck/emacs-travis/issues/13
sudo: required

cache:
  - directories:
      - "$HOME/emacs"

env:
  global:
    # Install Racket where sudo not required.
    - RACKET_DIR="$HOME/racket"
  matrix:
    # Emacs 24.3. To keep the matrix from growing too big/slow, test
    # only against recent versions of Racket. (Hopefully any problems
    # with older Rackets will be discovered elsewhere in the matrix
    # when testing with newer Emacs. Anyway, we're likely to drop
    # support for Emacs 24.3 soon.)
    - EMACS_VERSION=24.3 RACKET_VERSION=6.10
    - EMACS_VERSION=24.3 RACKET_VERSION=HEAD
    # Emacs 24.5
    - EMACS_VERSION=24.5 RACKET_VERSION=6.0
    - EMACS_VERSION=24.5 RACKET_VERSION=6.1
    - EMACS_VERSION=24.5 RACKET_VERSION=6.2
    - EMACS_VERSION=24.5 RACKET_VERSION=6.3
    - EMACS_VERSION=24.5 RACKET_VERSION=6.5
    - EMACS_VERSION=24.5 RACKET_VERSION=6.6
    - EMACS_VERSION=24.5 RACKET_VERSION=6.7
    - EMACS_VERSION=24.5 RACKET_VERSION=6.8
    - EMACS_VERSION=24.5 RACKET_VERSION=6.9
    - EMACS_VERSION=24.5 RACKET_VERSION=6.10
    - EMACS_VERSION=24.5 RACKET_VERSION=HEAD
    # Emacs 25.1
    - EMACS_VERSION=25.1 RACKET_VERSION=6.0
    - EMACS_VERSION=25.1 RACKET_VERSION=6.1
    - EMACS_VERSION=25.1 RACKET_VERSION=6.2
    - EMACS_VERSION=25.1 RACKET_VERSION=6.3
    - EMACS_VERSION=25.1 RACKET_VERSION=6.5
    - EMACS_VERSION=25.1 RACKET_VERSION=6.6
    - EMACS_VERSION=25.1 RACKET_VERSION=6.7
    - EMACS_VERSION=25.1 RACKET_VERSION=6.8
    - EMACS_VERSION=25.1 RACKET_VERSION=6.9
    - EMACS_VERSION=25.1 RACKET_VERSION=6.10
    - EMACS_VERSION=25.1 RACKET_VERSION=HEAD
    # Emacs snapshot. Because slow to make, test against only some key
    # versions of Racket like latest stable and HEAD. Also list these
    # jobs below under `allow_failures`, and use `fast_finish`.
    - EMACS_VERSION=snapshot RACKET_VERSION=6.10
    - EMACS_VERSION=snapshot RACKET_VERSION=HEAD

matrix:
  allow_failures:
    # bleeding edge Racket
    - env: EMACS_VERSION=24.3 RACKET_VERSION=HEAD
    - env: EMACS_VERSION=24.5 RACKET_VERSION=HEAD
    - env: EMACS_VERSION=25.1 RACKET_VERSION=HEAD
    # bleeding edge Emacs
    - env: EMACS_VERSION=snapshot RACKET_VERSION=6.10
    - env: EMACS_VERSION=snapshot RACKET_VERSION=HEAD
  fast_finish: true

before_install:
  ## Emacs
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION)
  - make -f emacs-travis.mk install_emacs
  # # Install Texinfo, if you need to build info manuals for your project
  # - make -f emacs-travis.mk install_texinfo

  ## Racket
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
  - make deps
  - make compile
  - make test
