#!/usr/bin/env python3

# Script main entry

import os
import sys

coredirname = "tt-core"
okapidirname = ".."  # okapi path
helpdoc = None

def main():
    # add import path
    srcdir = os.path.dirname(os.path.realpath(__file__))
    srcdir = srcdir.replace("\\", "/")
    sys.path.append(os.path.join(srcdir, okapidirname))

    from utils import common
    from framework import dispatch

    common.setcoredir(coredirname)
    workdir = common.getworkdir()
    dispatcher = dispatch.Dispatch(workdir, srcdir, sys.argv, helpdoc)
    dispatcher.run()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\nUser Press Ctrl+C, exit\n")
